resources:
  - name: helm_hub_sync_any_branch
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/helm-hub-sync
      branches: 
        exclude: master

pipelines:
  - name: helmHubSyncAnybranch
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            DESIRED_VERSION: v2.14.3
          inputResources:
            - name: helm_hub_sync_any_branch
        execution:
          onExecute:
            - cd $res_helm_hub_sync_any_branch_resourcePath
            - ls
            - pwd
            - gcloud version
            - echo "Release"
