resources:
  - name: helm_hub_sync_master
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/helm-hub-sync
      #files:
      #  exclude: .pipelines/.*\.yml
      branches: 
        include: master

pipelines:
  - name: helmHubSyncMaster
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            DESIRED_VERSION: v2.14.3
          inputResources:
            - name: helm_hub_sync_master
        execution:
          onExecute:
            - cd $res_helm_hub_sync_master_resourcePath
            - docker version
            - pwd
            - gcloud version
            - echo "Release"
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: buildGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: helm-hub-sync
          dockerImageTag: $run_number
          inputResources:
            - name: helm_hub_sync_master
      - name: goreleaser
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.12.9"
          inputResources:
            - name: helm_hub_sync_master
        execution:
          onExecute:
            - cd $res_helm_hub_sync_master_resourcePath
            - ls
            - go version
            - echo "goreleaser finished!!!" 
