resources:
  - name: helm_hub_sync_master
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/helm-hub-sync
      #files:
      #  exclude: .pipelines/.*\.yml
      branches: 
        include: master

pipelines:
  - name: helmHubSyncMaster
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            DOCKER_VERSION: 18.09.6
            DESIRED_VERSION: v2.14.3
          inputResources:
            - name: helm_hub_sync_master
        execution:
          onExecute:
            - wget https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz -P /tmp/docker && \
              tar -xzf /tmp/docker/docker-$DOCKER_VERSION.tgz --directory /opt && \
              ln -s /opt/docker/docker /usr/bin/docker && rm -rf /tmp/docker
            - cd $res_helm_hub_sync_master_resourcePath
            - ls -alh /usr/bin/docker
            - /usr/bin/docker
            - cat /var/run/docker.sock
            - pwd
            - gcloud version
            - echo "Release"
