resources:
  - name: helm_hub_sync_master
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/helm-hub-sync
      files:
        exclude: .pipelines/.*\.yml
      branches: 
        include: master

pipelines:
  - name: helmHubSyncMaster
    steps:
      - name: build_image
        type: DockerBuild
        configuration:
          affinityGroup: buildGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: art.example.com/docker/helm-hub-sync
          dockerImageTag: $run_number
          inputResources:
            - name: helm_hub_sync_master

