resources:
  - name: helm_hub_sync_master
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/helm-hub-sync
      #files:
      #  exclude: .pipelines/.*\.yml
      branches: 
        include: master

pipelines:
  - name: helmHubSyncMaster
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            DESIRED_VERSION: v2.14.3
          inputResources:
            - name: helm_hub_sync_master
        execution:
          onExecute:
            - cd $res_helm_hub_sync_master_resourcePath
            - ls -alh /usr/bin/docker
            - /usr/bin/docker
            - cat /var/run/docker.sock
            - pwd
            - gcloud version
            - echo "Release"

