resources:
  - name: helm_hub_sync_pr
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/helm-hub-sync
      files:
        exclude: .pipelines/.*.yml$
      branches:
        include: master
      buildOn:
        commit: false
        pullRequestCreate: true

pipelines:
  - name: helmHubSyncPr
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            DESIRED_VERSION: v2.14.3
          inputResources:
            - name: helm_hub_sync_pr
        execution:
          onExecute:
            - cd $res_helm_hub_sync_pr_resourcePath
            - ls
            - pwd
            - echo "PR against to master"
