resources:
  - name: helm_hub_sync_tag
    type: GitRepo
    configuration:
      gitProvider: rimas_github
      path: rimusz/helm-hub-sync
      tags:
        include: .*.*.*
      buildOn:
        commit: false
        tagCreate: true

pipelines:
  - name: helmHubSyncTag
    steps:
      - name: run
        type: Bash
        configuration:
          environmentVariables:
            DESIRED_VERSION: v2.14.3
          inputResources:
            - name: helm_hub_sync_tag
        execution:
          onExecute:
            - cd $res_helm_hub_sync_tag_resourcePath
            - ls
            - pwd
            - gcloud version
            - echo "Tag"
